### ISSUE TITLE
Project Structure Dialog NullPointerException

### ISSUE THREAD

**Issue by enra64** [sylvanaar/IDLua#10]
I think this is the same issue as #3, but I'm not quite sure. The relevant exception occurs when clicking the File>Project Structure button in IntelliJ:

```null
java.lang.AbstractMethodError
	at com.intellij.openapi.roots.libraries.LibraryPresentationProvider.getIcon(LibraryPresentationProvider.java:59)
	at com.intellij.openapi.roots.libraries.LibraryPresentationProvider.getIcon(LibraryPresentationProvider.java:65)
	at com.sylvanaar.idea.Lua.library.LuaLibraryType.getIcon(LuaLibraryType.java:89)
	at com.sylvanaar.idea.Lua.library.LuaLibraryType.getIcon(LuaLibraryType.java:38)
	at com.intellij.openapi.roots.ui.configuration.libraries.impl.LibraryPresentationManagerImpl$2.processProperties(LibraryPresentationManagerImpl.java:112)
	at com.intellij.openapi.roots.impl.libraries.LibraryDetectionManagerImpl.processProperties(LibraryDetectionManagerImpl.java:41)
	at com.intellij.openapi.roots.ui.configuration.libraries.impl.LibraryPresentationManagerImpl.getCustomIcons(LibraryPresentationManagerImpl.java:107)
	at com.intellij.openapi.roots.ui.configuration.libraries.impl.LibraryPresentationManagerImpl.getCustomIcon(LibraryPresentationManagerImpl.java:95)
	at com.intellij.openapi.roots.ui.OrderEntryAppearanceServiceImpl.forLibrary(OrderEntryAppearanceServiceImpl.java:98)
	at com.intellij.openapi.roots.ui.OrderEntryAppearanceServiceImpl.forOrderEntry(OrderEntryAppearanceServiceImpl.java:78)
	at com.intellij.openapi.roots.ui.configuration.classpath.ClasspathPanelImpl.getCellAppearance(ClasspathPanelImpl.java:701)
	at com.intellij.openapi.roots.ui.configuration.classpath.ClasspathPanelImpl$TableItemRenderer.customizeCellRenderer(ClasspathPanelImpl.java:720)
	at com.intellij.ui.ColoredTableCellRenderer.getTableCellRendererComponent(ColoredTableCellRenderer.java:36)
	at com.intellij.ui.table.JBTable.calculateRowHeight(JBTable.java:164)
	at com.intellij.ui.table.JBTable.getRowHeight(JBTable.java:142)
	at javax.swing.JTable.getRowHeight(JTable.java:992)
	at javax.swing.JTable.getCellRect(JTable.java:2937)
	at javax.swing.JTable.valueChanged(JTable.java:4698)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:405)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:415)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:459)
	at com.intellij.openapi.roots.ui.configuration.classpath.ClasspathPanelImpl.<init>(ClasspathPanelImpl.java:248)
	at com.intellij.openapi.roots.ui.configuration.ClasspathEditor.createComponentImpl(ClasspathEditor.java:97)
	at com.intellij.openapi.roots.ui.configuration.ModuleElementsEditor.createComponent(ModuleElementsEditor.java:86)
	at com.intellij.openapi.roots.ui.configuration.TabbedModuleEditor.createCenterPanel(TabbedModuleEditor.java:61)
	at com.intellij.openapi.roots.ui.configuration.HeaderHidingTabbedModuleEditor.createCenterPanel(HeaderHidingTabbedModuleEditor.java:30)
	at com.intellij.openapi.roots.ui.configuration.ModuleEditor.a(ModuleEditor.java:264)
	at com.intellij.openapi.roots.ui.configuration.ModuleEditor.getPanel(ModuleEditor.java:272)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ModuleConfigurable.createOptionsPanel(ModuleConfigurable.java:134)
	at com.intellij.openapi.ui.NamedConfigurable.createComponent(NamedConfigurable.java:93)
	at com.intellij.openapi.ui.MasterDetailsComponent.updateSelection(MasterDetailsComponent.java:666)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ModuleStructureConfigurable.updateSelection(ModuleStructureConfigurable.java:191)
	at com.intellij.openapi.ui.MasterDetailsComponent.setSelectedNode(MasterDetailsComponent.java:657)
	at com.intellij.openapi.ui.MasterDetailsComponent.updateSelectionFromTree(MasterDetailsComponent.java:247)
	at com.intellij.openapi.ui.MasterDetailsComponent.reset(MasterDetailsComponent.java:385)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.BaseStructureConfigurable.reset(BaseStructureConfigurable.java:264)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ModuleStructureConfigurable.reset(ModuleStructureConfigurable.java:345)
	at com.intellij.openapi.roots.ui.configuration.ProjectStructureConfigurable.reset(ProjectStructureConfigurable.java:362)
	at com.intellij.openapi.options.ex.SingleConfigurableEditor.<init>(SingleConfigurableEditor.java:67)
	at com.intellij.openapi.options.ex.SingleConfigurableEditor.<init>(SingleConfigurableEditor.java:89)
	at com.intellij.openapi.options.ex.SingleConfigurableEditor.<init>(SingleConfigurableEditor.java:104)
	at com.intellij.ide.actions.ShowStructureSettingsAction$1.<init>(ShowStructureSettingsAction.java:45)
	at com.intellij.ide.actions.ShowStructureSettingsAction.showDialog(ShowStructureSettingsAction.java:45)
	at com.intellij.ide.actions.ShowStructureSettingsAction.actionPerformed(ShowStructureSettingsAction.java:41)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:151)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:230)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.a(ActionMenuItem.java:309)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:929)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:136)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:299)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.a(ActionMenuItem.java:116)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:109)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:118)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:116)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:513)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.i(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:651)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)```

I hope that with more information this can be fixed; i'm not sure if it still exists, because the line numbers don't make sense.

# Version Info

## Plugin
My plugin version is 1.0.109. 

## IntelliJ
IntelliJ IDEA 2017.1.5
Build #IU-171.4694.70, built on July 4, 2017
JRE: 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11 amd64
JVM: OpenJDK 64-Bit Server VM by Oracle Corporation
Linux 4.8.0-58-generic

**Comment by ypujante** [comment]
I filed a similar issue with JetBrains: https://youtrack.jetbrains.com/issue/IDEA-177177

After installing this plugin it is no longer possible to add global libraries.
